apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: hostpath

  resources:
    requests:
      storage: 1Gi
